### ISSUE TITLE
[NUM-1507] `docker-compose up` errors

### ISSUE THREAD

**Issue by sbue** [formancehq/stack#54]
First error:
```
ERROR: The Compose file './docker-compose.yml' is invalid because:
services.auth.environment.DEBUG contains true, which is an invalid type, it should be a string, number, or a null
```
I re-rewrite the line `DEBUG: true` -> `DEBUG: "true"` and now get the following error:
```
Traceback (most recent call last):
  File "urllib3/connectionpool.py", line 670, in urlopen
  File "urllib3/connectionpool.py", line 392, in _make_request
  File "http/client.py", line 1255, in request
  File "http/client.py", line 1301, in _send_request
  File "http/client.py", line 1250, in endheaders
  File "http/client.py", line 1010, in _send_output
  File "http/client.py", line 950, in send
  File "docker/transport/unixconn.py", line 43, in connect
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:
```

<sub>[NUM-1507](https://linear.app/formance/issue/NUM-1507/docker-compose-up-errors)</sub>

**Comment by flemzord** [comment]
Thank you for your feedback @sbue ! 
On our side, we use docker compose v2: "docker compose". 
I think there must be some incompatibilities between the two, we are looking into it.
